version: '3.8'
services:
    # Todo: 1. Service Search
    service_search:
        container_name: service_search
        depends_on:
            - elastic-search
            - kibana
        restart: always
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        environment:
            - NODE_ENV=${NODE_ENV}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - './src:/usr/src/app/src'
        env_file:
            - .env
        command: yarn dev
        networks:
            - service_search_service-network

    # Todo: 2. Elastic search
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
        environment:
            node.name: elasticsearch
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
            - elasticsearch-data:/usr/share/elasticsearch/data:Z
        ports:
            - ${ELASTIC_SEARCH_PORT}:${ELASTIC_SEARCH_PORT}
        env_file:
            - .env
        networks:
        - elk

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:8.4.3
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_HOSTS: ${ELASTIC_SEARCH_HOST:-}
            ELASTICSEARCH_SERVICEACCOUNTTOKEN: ${ELASTIC_TOKEN:-}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        links:
            - elasticsearch
        ports:
            - ${KIBANA_PORT}:${KIBANA_PORT}
        env_file:
            - .env
        networks:
            - elk
networks:
    elk:
        driver: bridge

volumes:
    elasticsearch-data:
        driver: local
